server:
  port: 8081

logging:
  level:
    com:
      example: debug
spring:
  datasource:
    url: jdbc:mysql://150.158.19.8:23306/chatbi?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: liqing123..
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml